# Headless Service 생성 (StatefulSet 용)
apiVersion: v1
kind: Service
metadata:
  name: nginx-headless
spec:
  selector:
    app: nginx-stateful
  ports:
  - port: 80
    targetPort: 80
  clusterIP: None
